CXX=../g++
CURRENT_DIR := $(shell pwd)
SOURCE_DIR := $(CURRENT_DIR)/src
INCLUDE_DIR := $(CURRENT_DIR)/include

$(OUTPUT_PATH_SRC)/%.o: $(SOURCE_DIR)/%.cpp $(INCLUDE_DIR)/%.hpp 
	@mkdir -p $(OUTPUT_PATH_SRC)
	$(CXX) $(CPPFLAGS) -c $< -o $@

$(OUTPUT_PATH_SRC)/%.o: $(SOURCE_DIR)/%.cpp 
	@mkdir -p $(OUTPUT_PATH_SRC)
	$(CXX) $(CPPFLAGS) -c $< -o $@